const communityStandardsViolations = [
    "bạo lực",
    "ngu ngốc",
    "lạm dụng",
    "quấy rối",
    "kỳ thị",
    "phân biệt chủng tộc",
    "phân biệt giới tính",
    "kích động thù hận",
    "tuyên truyền khủng bố",
    "khiêu dâm",
    "nội dung đồi trụy",
    "hình ảnh tục tĩu",
    "ảnh khỏa thân",
    "ảnh bạo lực",
    "ảnh máu me",
    "xúc phạm",
    "lời lẽ xúc phạm",
    "ngôn từ thù ghét",
    "phỉ báng",
    "chửi thề",
    "ngôn từ tục tĩu",
    "lừa đảo",
    "gian lận",
    "quảng cáo giả",
    "hàng giả",
    "thông tin sai lệch",
    "tin giả",
    "phao tin đồn nhảm",
    "thông tin gây hoang mang",
    "tin đồn thất thiệt",
    "bắt nạt",
    "đe dọa",
    "ép buộc",
    "tống tiền",
    "hành vi quấy rối",
    "cưỡng ép",
    "lừa dối",
    "gian lận tài chính",
    "tiền bẩn",
    "buôn bán ma túy",
    "buôn bán chất cấm",
    "mua bán người",
    "mại dâm",
    "buôn bán vũ khí",
    "vũ khí nóng",
    "súng đạn",
    "thuốc lắc",
    "chất gây nghiện",
    "bạch phiến",
    "hồng phiến",
    "ma túy đá",
    "thuốc phiện",
    "chất kích thích",
    "thuốc lắc",
    "chất cấm",
    "hóa chất độc hại",
    "chất độc",
    "bơm silicon lậu",
    "phá thai lậu",
    "nạo phá thai",
    "giao dịch trái phép",
    "vi phạm bản quyền",
    "ăn cắp bản quyền",
    "xâm phạm quyền riêng tư",
    "hình ảnh riêng tư",
    "video riêng tư",
    "tin nhắn riêng tư",
    "thông tin cá nhân",
    "dữ liệu cá nhân",
    "hack tài khoản",
    "xâm nhập hệ thống",
    "phần mềm độc hại",
    "virus máy tính",
    "phần mềm gián điệp",
    "mã độc",
    "tấn công mạng",
    "tấn công DDoS",
    "lừa đảo trực tuyến",
    "gian lận qua mạng",
    "tài liệu khiêu dâm trẻ em",
    "lạm dụng trẻ em",
    "bạo lực gia đình",
    "bạo lực trẻ em",
    "bạo hành",
    "bắt nạt trực tuyến",
    "đánh đập",
    "ngược đãi động vật",
    "tra tấn động vật",
    "giết hại động vật",
    "bán động vật quý hiếm",
    "mua bán động vật hoang dã",
    "săn bắn trái phép",
    "cướp giật",
    "trộm cắp",
    "đánh nhau",
    "bạo loạn",
    "khủng bố",
    "nội dung cực đoan",
    "tư tưởng cực đoan",
    "lực lượng vũ trang phi pháp",
    "tổ chức khủng bố",
    "nhóm khủng bố",
    "chủ nghĩa khủng bố",
    "tôn giáo cực đoan",
    "tôn giáo phản động",
    "nội dung phản động",
    "phản cách mạng",
    "chống đối chính quyền",
    "lật đổ chính quyền",
    "biểu tình bạo lực",
    "bạo động",
    "xâm phạm an ninh quốc gia",
    "xâm phạm lãnh thổ",
    "gián điệp",
    "hoạt động gián điệp",
    "tình báo",
    "tình báo gián điệp",
    "buôn lậu",
    "buôn lậu hàng hóa",
    "buôn lậu động vật",
    "buôn lậu ma túy",
    "buôn lậu vũ khí",
    "hành vi tham nhũng",
    "hối lộ",
    "tham nhũng",
    "mua bán phiếu bầu",
    "lừa đảo bầu cử",
    "gian lận bầu cử",
    "thao túng bầu cử",
    "bỏ phiếu giả",
    "phiếu bầu giả",
    "tổ chức tội phạm",
    "băng đảng",
    "băng nhóm",
    "xã hội đen",
    "mafia",
    "bố già",
    "đầu gấu",
    "băng đảng ma túy",
    "băng đảng tội phạm",
    "băng đảng vũ trang",
    "văn hóa phẩm đồi trụy",
    "sách báo khiêu dâm",
    "truyện tranh khiêu dâm",
    "video khiêu dâm",
    "phim khiêu dâm",
    "truyện sex",
    "truyện người lớn",
    "phim người lớn",
    "web sex",
    "trang web khiêu dâm",
    "điện thoại sex",
    "dịch vụ sex",
    "cuộc gọi sex",
    "chương trình sex",
    "show sex",
    "nội dung khiêu dâm",
    "ảnh nóng",
    "video nóng",
    "ảnh sex",
    "clip sex",
    "đồ chơi tình dục",
    "sản phẩm tình dục",
    "chợ đen",
    "thị trường chợ đen",
    "kinh doanh trái phép",
    "giao dịch trái phép",
    "mua bán trái phép",
    "vận chuyển trái phép",
    "hàng cấm",
    "vật phẩm cấm",
    "sản phẩm cấm",
    "hàng lậu",
    "hàng giả",
    "hàng nhái",
    "sản phẩm giả",
    "thực phẩm bẩn",
    "thực phẩm độc hại",
    "hóa chất độc hại",
    "chất độc",
    "thuốc giả",
    "dược phẩm giả",
    "sản phẩm giả mạo",
    "thực phẩm giả",
    "hành vi lừa đảo",
    "lừa đảo qua mạng",
    "gian lận qua mạng",
    "gian lận tài chính",
    "tiền bẩn",
    "buôn bán ma túy",
    "buôn bán chất cấm",
    "mua bán người",
    "mại dâm",
    "buôn bán vũ khí",
    "vũ khí nóng",
    "súng đạn",
    "thuốc lắc",
    "chất gây nghiện",
    "bạch phiến",
    "hồng phiến",
    "ma túy đá",
    "thuốc phiện",
    "chất kích thích",
    "thuốc lắc",
    "chất cấm",
    "hóa chất độc hại",
    "chất độc",
    "bơm silicon lậu",
    "phá thai lậu",
    "nạo phá thai",
    "giao dịch trái phép",
    "vi phạm bản quyền",
    "ăn cắp bản quyền",
    "xâm phạm quyền riêng tư",
    "hình ảnh riêng tư",
    "video riêng tư",
    "tin nhắn riêng tư",
    "thông tin cá nhân",
    "dữ liệu cá nhân",
    "hack tài khoản",
    "xâm nhập hệ thống",
    "phần mềm độc hại",
    "virus máy tính",
    "phần mềm gián điệp",
    "mã độc",
    "tấn công mạng",
    "tấn công DDoS",
    "lừa đảo trực tuyến",
    "gian lận qua mạng",
    "tài liệu khiêu dâm trẻ em",
    "lạm dụng trẻ em",
    "bạo lực gia đình",
    "bạo lực trẻ em",
    "bạo hành",
    "bắt nạt trực tuyến",
    "đánh đập",
    "ngược đãi động vật",
    "tra tấn động vật",
    "giết hại động vật",
    "bán động vật quý hiếm",
    "mua bán động vật hoang dã",
    "săn bắn trái phép",
    "bạo lực",
    "lạm dụng",
    "quấy rối",
    "kỳ thị",
    "phân biệt",
    "thù hận",
    "khủng bố",
    "khiêu dâm",
    "đồi trụy",
    "tục tĩu",
    "khỏa thân",
    "máu me",
    "xúc phạm",
    "phỉ báng",
    "chửi thề",
    "gian lận",
    "lừa đảo",
    "hàng giả",
    "tin giả",
    "đồn nhảm",
    "hoang mang",
    "bắt nạt",
    "đe dọa",
    "ép buộc",
    "tống tiền",
    "cưỡng ép",
    "lừa dối",
    "buôn lậu",
    "ma túy",
    "vũ khí",
    "mại dâm",
    "hối lộ",
    "tham nhũng",
    "bạo hành",
    "mua bán",
    "phá thai",
    "hack",
    "gián điệp",
    "giết hại",
    "trộm cắp",
    "đánh nhau",
    "bạo loạn",
    "cực đoan",
    "băng đảng",
    "mafia",
    "xã hội đen",
    "buôn người",
    "khủng bố",
    "nội dung",
    "tình dục",
    "sách báo",
    "video",
    "clip",
    "truyện sex",
    "web sex",
    "show sex",
    "đồ chơi",
    "sản phẩm",
    "chợ đen",
    "giao dịch",
    "hàng cấm",
    "vật phẩm",
    "thực phẩm",
    "hóa chất",
    "thuốc giả",
    "dược phẩm",
    "sản phẩm",
    "quảng cáo",
    "xúc phạm",
    "kỳ thị",
    "nói xấu",
    "chống đối",
    "phản động",
    "phản cách mạng",
    "bất mãn",
    "lừa dối",
    "chống đối",
    "chửi bới",
    "thô tục",
    "tục tĩu",
    "khiêu khích",
    "công kích",
    "xâm phạm",
    "quấy nhiễu",
    "quấy rối",
    "đe dọa",
    "ép buộc",
    "mắng mỏ",
    "khiêu khích",
    "kích động",
    "hận thù",
    "bôi nhọ",
    "xúc phạm",
    "khinh thường",
    "bài xích",
    "phân biệt",
    "phỉ báng",
    "nhục mạ",
    "chê bai",
    "khiêu khích",
    "công kích",
    "xâm phạm",
    "lạm dụng",
    "ép buộc",
    "quấy nhiễu",
    "xâm hại",
    "xúc phạm",
    "phỉ báng",
    "kỳ thị",
    "công kích",
    "kích động",
    "kỳ thị",
    "bài xích",
    "nhục mạ",
    "phân biệt",
    "xâm hại",
    "quấy rối",
    "công kích",
    "tẩy chay",
    "ép buộc",
    "xúc phạm",
    "bôi nhọ",
    "kỳ thị",
    "phân biệt",
    "hận thù",
    "công kích",
    "quấy rối",
    "xâm phạm",
    "lừa đảo",
    "gian lận",
    "quấy rối",
    "xâm hại",
    "phỉ báng",
    "kỳ thị",
    "công kích",
    "kỳ thị",
    "bôi nhọ",
    "xâm hại",
    "quấy rối",
    "ép buộc",
    "kỳ thị",
    "hận thù",
    "phân biệt",
    "phỉ báng",
    "xúc phạm",
    "quấy nhiễu",
    "xâm phạm",
    "ép buộc",
    "lừa đảo",
    "phỉ báng",
    "công kích",
    "kỳ thị",
    "xâm hại",
    "quấy rối",
    "ép buộc",
    "công kích",
    "kỳ thị",
    "bôi nhọ",
    "xâm phạm",
    "quấy nhiễu",
    "phỉ báng",
    "kỳ thị",
    "hận thù",
    "công kích",
    "phân biệt",
    "xâm hại",
    "quấy rối",
    "ép buộc",
    "lừa đảo",
    "công kích",
    "kỳ thị",
    "bôi nhọ",
    "xâm phạm",
    "quấy nhiễu",
    "phỉ báng",
    "kỳ thị",
    "hận thù",
    "công kích",
    "phân biệt",
    "xâm hại",
    "quấy rối",
    "ép buộc",
    "lừa đảo",
    "công kích",
    "kỳ thị",
    "bôi nhọ",
    "xâm phạm",
    "quấy nhiễu",
    "phỉ báng",
    "kỳ thị",
    "hận thù",
    "công kích",
    "phân biệt",
    "xâm hại",
    "quấy rối",
    "ép buộc",
    "lừa đảo",
    "công kích",
    "kỳ thị",
    "bôi nhọ",
    "xâm phạm",
    "quấy nhiễu",
    "phỉ báng",
    "kỳ thị",
    "hận thù",
    "công kích",
    "phân biệt",
    "xâm hại",
    "quấy rối",
    "ép buộc",
    "lừa đảo",
    "công kích",
    "kỳ thị",
    "bôi nhọ",
    "xâm phạm",
    "quấy nhiễu",
    "phỉ báng",
    "kỳ thị",
    "hận thù",
    "công kích",
    "phân biệt",
    "xâm hại",
    "quấy rối",
    "ép buộc",
    "lừa đảo",
    "công kích",
    "kỳ thị",
    "bôi nhọ",
    "xâm phạm",
    "quấy nhiễu",
    "phỉ báng",
    "kỳ thị",
    "hận thù",
    "công kích",
    "phân biệt",
    "xâm hại",
    "quấy rối",
    "ép buộc",
    "lừa đảo",
    "công kích",
    "kỳ thị",
    "bôi nhọ",
    "xâm phạm",
    "quấy nhiễu",
    "phỉ báng",
    "kỳ thị",
    "hận thù",
    "công kích",
    "phân biệt",
    "xâm hại",
    "quấy rối",
    "ép buộc",
    "lừa đảo",
    "công kích",
    "kỳ thị",
    "bôi nhọ",
    "xâm phạm",
    "quấy nhiễu",
    "phỉ báng",
    "kỳ thị",
    "hận thù",
    "công kích",
    "phân biệt",
    "xâm hại",
    "quấy rối",
    "ép buộc",
    "lừa đảo",
    "công kích",
    "kỳ thị",
    "bôi nhọ",
    "xâm phạm",
    "quấy nhiễu",
    "phỉ báng",
    "kỳ thị",
    "hận thù",
    "công kích",
    "phân biệt",
    "xâm hại",
    "quấy rối",
    "ép buộc",
    "lừa đảo",
    "công kích",
    "kỳ thị",
    "bôi nhọ",
    "xâm phạm",
    "quấy nhiễu",
    "phỉ báng",
    "kỳ thị",
    "hận thù",
    "công kích",
    "phân biệt",
    "xâm hại",
    "quấy rối",
    "ép buộc",
    "lừa đảo",
    "công kích",
    "kỳ thị",
    "bôi nhọ",
    "xâm phạm",
    "quấy nhiễu",
    "phỉ báng",
    "kỳ thị",
    "hận thù",
    "công kích",
    "phân biệt",
    "xâm hại",
    "quấy rối",
    "ép buộc",
];

module.exports = communityStandardsViolations;